meta:
  random:
    - "{1-$$__mywc/meta/composition/do__|__mywc/meta/effect/do__|__mywc/meta/style/do__}"
  composition:
    do:
      - __mywc/meta/composition/angle/x__,__mywc/meta/composition/range__
      - __mywc/meta/composition/angle/y__
    angle:
      x:
        - " "
        - dutch angle
        - from side
      y:
        - from above
        - from below
    range:
      - " "
      - full body
      - upper body
  effect:
    do:
      - "{10::|1::__mywc/meta/effect/list__}"
    list:
      - depth of field
      - bokeh
      - foreshortening
  style:
    do:
      - anime coloring
      - __mywc/meta/style/list__
      - __mywc/style/artist/quality/*__
      - __mywc/style/production/quality/*__
    list:
      - photorealistic
      - pixel art
      - realistic
      - watercolor \(medium\)
  boilerplate:
    code:
      - __mywc/meta/boilerplate/quality__,__mywc/meta/boilerplate/numof-subjects__,
    quality:
      - masterpiece,best quality,amazing quality
    numof-subjects:
      - 1girl,solo
