meta:
  random:
    - __mywc/meta/composition/random__{9::|2::,__mywc/meta/effect__|1::,__mywc/meta/artstyle__}
  composition:
    random:
      - __mywc/meta/composition/from-above/do__
      - __mywc/meta/composition/from-below/do__
      - __mywc/meta/composition/from-side/do__
      - __mywc/meta/composition/pov/do__
      - __mywc/meta/composition/shot/do__
    from-above:
      do:
        - from above{|,__mywc/meta/composition/from-above/los__}
      los:
        - looking ahead
        - looking at another
        - looking at viewer
        - looking up
    from-below:
      do:
        - from below{|,__mywc/meta/composition/from-below/los__}
      los:
        - __mywc/meta/composition/from-below/pov-bool__
        - looking ahead
        - looking at another
        - looking at viewer,__mywc/meta/composition/from-below/pov-bool__
        - looking down,__mywc/meta/composition/from-below/pov-bool__
      pov-bool:
        - " "
        - pov
    from-side:
      do:
        - from side{|,__mywc/meta/composition/from-side/los__}
      los:
        - looking ahead
        - looking at another
        - looking at viewer
        - looking away
        - looking down
        - looking up
    pov:
      do:
        - pov{|,__mywc/meta/composition/pov/los__}
      los:
        - " "
        - looking at another
        - looking at viewer
    shot:
      do:
        - __mywc/meta/composition/shot/range__{|,__mywc/meta/composition/shot/los__}
      range:
        - dutch angle
        - full body
        - upper body
      los:
        - looking ahead
        - looking at another
        - looking at viewer
        - looking away
        - looking down
        - looking up
  effect:
    - depth of field
    - bokeh
    - foreshortening
  artstyle:
    - 3d model
    - line art
    - manga style
    - oil painting
    - photorealistic
    - pixel art
    - realistic
    - vector art
    - watercolor
